name: firebase
version: 0.6.5+1
authors:
- Anant Narayanan <anant@kix.in>
- Kevin Moore <github@j832.com>
- Flutter Authors <flutter-dev@googlegroups.com>
description: A Dart wrapper for Firebase.
homepage: https://github.com/firebase/firebase-dart/
environment:
  sdk: '>=1.9.0 <2.0.0'
dependencies:
  crypto: ^0.9.0
  http: ^0.11.2
dev_dependencies:
  test: ^0.12.0
